name: External validation

on:
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        uses: pnp/validate-sample-action@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
