name: External validation

on:
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
    steps:
      - name: Validate
        uses: Balastrong/validate-sample-action@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
